### ISSUE TITLE
Error en la Instalación

### ISSUE THREAD

**Issue by uri983** [rafaelcetina/ApiTables#1]
Tengo problemas al instalar en laravel 5.2 , me marca error al ejecutar Composer Update``

`
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "apiqroo/apitable" : "dev-master"
    },`

**Comment by rafaelcetina** [comment]
Desinstala windows pls
